apiVersion: v1
kind: Service
metadata:
  name: serviceapi-service
  labels:
    run: serviceapi-service
spec:
  selector:
    app: serviceapi-pod
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  type: LoadBalancer