apiVersion: v1
kind: Service
metadata:
  name: database-tier-service
  labels:
    app: database-tier
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: database-tier